### ISSUE TITLE
Crashes at Launch

### ISSUE THREAD

**Issue by joshkerr** [TryFetch/Fetch#22]
Using the latest release version on iOS 11 fully patched to 11.2.1 on both iPhone X and IPad Pro.

After a while Fetch gets into a state where it crashes on launch. It launches but before it can paint the main window it immediately quits. I’ve seen this behavior on both of my iOS devices. Seems like it happens around the same time. Starts happening on one and then the other. The only way I can get it to work again is to remove it and reinstall it.

**Comment by kylef** [comment]
I think this is likely the provision profile or something similar expiring, depending on how you are building and loading the application onto your device. Unfortunately iOS gives no indication of this and just kills the app on launch.

**Comment by joshkerr** [comment]
It turned out to be an expired provision profile. You can close this issue. Thanks!
