### ISSUE TITLE
Build error when trying to build project (Cannot find Alamofire)

### ISSUE THREAD

**Issue by joshkerr** [TryFetch/Fetch#23]
I pulled down the latest project files. Installed xcode 8.3.3. Successfully ran ./prepare with no errors. Launch Xcode, select a device (iPhone 7 plus) and click run and Xcode reports a build error that it cannot find Alamofire.

See the screenshot:

<img width="1512" alt="screen shot 2017-12-16 at 4 31 03 pm" src="https://user-images.githubusercontent.com/17816/34074895-95aac578-e27e-11e7-81c5-04722454dc36.png">

**Comment by kylef** [comment]
@joshkerr Did you open `Fetch.xcworkspace` or `Fetch.xcproj`? Given the error perhaps the project was opened instead of the workspace.

**Comment by joshkerr** [comment]
Yep - that was it. Thanks.
